<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: baylamon
 * Date: Sun, 25 Nov 2018 11:12:52 +0100
 */

$conf['title'] = 'Anega Documentation';
$conf['license'] = 'cc-by-sa';
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
